server:
  port: 8082
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    url: jdbc:postgresql://localhost:5434/cart-db
    username: cart-db
    password: cart-db
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
      database-platform: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      resourceserver:
        jwt:
          #          # Configurations for running locally
          #          jwk-set-uri: http://localhost:8090/auth/realms/profile-service/protocol/openid-connect/certs
          #          issuer-uri: http://localhost:8090/auth/realms/profile-service
          # Configurations for running within Docker
          jwk-set-uri: http://localhost:8090/auth/realms/profile-service/protocol/openid-connect/certs
          issuer-uri: http://localhost:8090/auth/realms/profile-service
logging:
  level:
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.web: DEBUG